function body = format_summary(dataType, maxResult,  iter, ...
                               num_pixels, p_values, gammas, lambdas)

    body = sprintf(['📊 数据集: %s\n', ...
                    '🧪 最大准确率: %.4f\n', ...
                    '🔍 最佳参数组合:\n', ...
                    '    num_pixels = %d\n', ...
                    '    p_value    = %.2f\n', ...
                    '    gamma      = %g\n', ...
                    '    lambda     = %g\n', ...
                    '\n', ...
                    '📘 调参配置:\n', ...
                    '    迭代次数 iter     = %d\n', ...
                    '    num_pixels        = [%s]\n', ...
                    '    p_values          = [%s]\n', ...
                    '    gammas            = [%s]\n', ...
                    '    lambdas           = [%s]\n'], ...
                    dataType, maxResult, ...
                    iter, ...%                     maxParams(1), maxParams(2), maxParams(3), maxParams(4), 
                    num2str(num_pixels), ...
                    num2str(p_values, '%.2f '), ...
                    num2str(gammas, '%g '), ...
                    num2str(lambdas, '%g '));
end
